# Generated by Django 4.1.1 on 2022-09-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESchoolVR', '0005_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
