# Generated by Django 4.1.1 on 2022-09-30 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ESchoolVR', '0006_student_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='surname',
            new_name='lastname',
        ),
    ]
